version: '3.8'

services:
  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - DEBUG=1
    command: uv run python manage.py runserver 0.0.0.0:8000
